# Dangerous php functions list from this thread
# https://stackoverflow.com/questions/3115559/exploitable-php-functions

CAT_CMD_EXEC = "Command execution"
CAT_PHP_EXEC = "PHP code execution"
CAT_CALLBACK = "PHP injectable callbacks"
CAT_DISCLOSU = "Information disclosure"
CAT_DANGEROU = "PHP dangerous functions"
CAT_FILESYST = "Filesystem related"
CAT_WP_SPECI = "Wordpress specific"
CAT_PHP_INPU = "PHP Inputs"
CAT_PHP_MAGI = "PHP Magic functions"

TYPE_SOURCE = "source"
TYPE_SINK = "sink"

class Target:
    def __init__(self, category, name, target_type, metadata):
        self.category = category
        self.name = name
        self.target_type = target_type
        self.metadata = metadata

    def __repr__(self):
        return f"{self.category} || {self.name} || {self.target_type} || {self.metadata}"

# Sinks
command_exec = list()
command_exec.append(Target(CAT_CMD_EXEC, "shell_exec(", TYPE_SINK, None))
command_exec.append(Target(CAT_CMD_EXEC, "exec(", TYPE_SINK, None))
command_exec.append(Target(CAT_CMD_EXEC, "passthru(", TYPE_SINK, None))
command_exec.append(Target(CAT_CMD_EXEC, "system(", TYPE_SINK, None))
command_exec.append(Target(CAT_CMD_EXEC, "shell_exec(", TYPE_SINK, None))
command_exec.append(Target(CAT_CMD_EXEC, "popen(", TYPE_SINK, None))
command_exec.append(Target(CAT_CMD_EXEC, "proc_open(", TYPE_SINK, None))
command_exec.append(Target(CAT_CMD_EXEC, "pcntl_exec(", TYPE_SINK, None))
#command_exec += "``"

php_exec = list()
php_exec.append(Target(CAT_PHP_EXEC, "eval(", TYPE_SINK, None))
php_exec.append(Target(CAT_PHP_EXEC, "assert(", TYPE_SINK, None))
php_exec.append(Target(CAT_PHP_EXEC, "create_function(", TYPE_SINK, None))
php_exec.append(Target(CAT_PHP_EXEC, "include(", TYPE_SINK, None))
php_exec.append(Target(CAT_PHP_EXEC, "include_once(", TYPE_SINK, None))
php_exec.append(Target(CAT_PHP_EXEC, "require(", TYPE_SINK, None))
php_exec.append(Target(CAT_PHP_EXEC, "require_once(", TYPE_SINK, None))
php_exec.append(Target(CAT_PHP_EXEC, "ReflectionFunction(", TYPE_SINK, None))
php_exec.append(Target(CAT_PHP_EXEC, "invoke(", TYPE_SINK, None))
php_exec.append(Target(CAT_PHP_EXEC, "invokeArgs(", TYPE_SINK, None))
php_exec.append(Target(CAT_PHP_EXEC, "preg_replace(", TYPE_SINK, None))
# $func_name($argument);

callbacks = list() # Indexes of callbacks
callbacks.append(Target(CAT_CALLBACK, "ob_start(", TYPE_SINK, "# 0,"))
callbacks.append(Target(CAT_CALLBACK, "array_diff_uassoc(", TYPE_SINK, "# -1,"))
callbacks.append(Target(CAT_CALLBACK, "array_diff_ukey(", TYPE_SINK, "# -1,"))
callbacks.append(Target(CAT_CALLBACK, "array_filter(", TYPE_SINK, "# 1,"))
callbacks.append(Target(CAT_CALLBACK, "array_intersect_uassoc(", TYPE_SINK, "# -1,"))
callbacks.append(Target(CAT_CALLBACK, "array_intersect_ukey(", TYPE_SINK, "# -1,"))
callbacks.append(Target(CAT_CALLBACK, "array_map(", TYPE_SINK, "# 0,"))
callbacks.append(Target(CAT_CALLBACK, "array_reduce(", TYPE_SINK, "# 1,"))
callbacks.append(Target(CAT_CALLBACK, "array_udiff_assoc(", TYPE_SINK, "# -1,"))
callbacks.append(Target(CAT_CALLBACK, "array_udiff_uassoc(", TYPE_SINK, "# array(-1, -2),"))
callbacks.append(Target(CAT_CALLBACK, "array_udiff(", TYPE_SINK, "# -1,"))
callbacks.append(Target(CAT_CALLBACK, "array_uintersect_assoc(", TYPE_SINK, "# -1,"))
callbacks.append(Target(CAT_CALLBACK, "array_uintersect_uassoc(", TYPE_SINK, "# array(-1, -2),"))
callbacks.append(Target(CAT_CALLBACK, "array_uintersect(", TYPE_SINK, "# -1,"))
callbacks.append(Target(CAT_CALLBACK, "array_walk_recursive(", TYPE_SINK, "# 1,"))
callbacks.append(Target(CAT_CALLBACK, "array_walk(", TYPE_SINK, "# 1,"))
callbacks.append(Target(CAT_CALLBACK, "assert_options(", TYPE_SINK, "# 1,"))
callbacks.append(Target(CAT_CALLBACK, "uasort(", TYPE_SINK, "# 1,"))
callbacks.append(Target(CAT_CALLBACK, "uksort(", TYPE_SINK, "# 1,"))
callbacks.append(Target(CAT_CALLBACK, "usort(", TYPE_SINK, "# 1,"))
callbacks.append(Target(CAT_CALLBACK, "preg_replace_callback(", TYPE_SINK, "# 1,"))
callbacks.append(Target(CAT_CALLBACK, "spl_autoload_register(", TYPE_SINK, "# 0,"))
callbacks.append(Target(CAT_CALLBACK, "iterator_apply(", TYPE_SINK, "# 1,"))
callbacks.append(Target(CAT_CALLBACK, "call_user_func(", TYPE_SINK, "# 0,"))
callbacks.append(Target(CAT_CALLBACK, "call_user_func_array(", TYPE_SINK, "# 0,"))
callbacks.append(Target(CAT_CALLBACK, "register_shutdown_function(", TYPE_SINK, "# 0,"))
callbacks.append(Target(CAT_CALLBACK, "register_tick_function(", TYPE_SINK, "# 0,"))
callbacks.append(Target(CAT_CALLBACK, "set_error_handler(", TYPE_SINK, "# 0,"))
callbacks.append(Target(CAT_CALLBACK, "set_exception_handler(", TYPE_SINK, "# 0,"))
callbacks.append(Target(CAT_CALLBACK, "session_set_save_handler(", TYPE_SINK, "# array(0, 1, 2, 3, 4, 5),"))
callbacks.append(Target(CAT_CALLBACK, "sqlite_create_aggregate(", TYPE_SINK, "# array(2, 3),"))
callbacks.append(Target(CAT_CALLBACK, "sqlite_create_function(", TYPE_SINK, "# 2,"))

disclo = list()
disclo.append(Target(CAT_DISCLOSU, "phpinfo(", TYPE_SINK, None))
disclo.append(Target(CAT_DISCLOSU, "posix_mkfifo(", TYPE_SINK, None))
disclo.append(Target(CAT_DISCLOSU, "posix_getlogin(", TYPE_SINK, None))
disclo.append(Target(CAT_DISCLOSU, "posix_ttyname(", TYPE_SINK, None))
disclo.append(Target(CAT_DISCLOSU, "getenv(", TYPE_SINK, None))
disclo.append(Target(CAT_DISCLOSU, "get_current_user(", TYPE_SINK, None))
disclo.append(Target(CAT_DISCLOSU, "proc_get_status(", TYPE_SINK, None))
disclo.append(Target(CAT_DISCLOSU, "get_cfg_var(", TYPE_SINK, None))
disclo.append(Target(CAT_DISCLOSU, "disk_free_space(", TYPE_SINK, None))
disclo.append(Target(CAT_DISCLOSU, "disk_total_space(", TYPE_SINK, None))
disclo.append(Target(CAT_DISCLOSU, "diskfreespace(", TYPE_SINK, None))
disclo.append(Target(CAT_DISCLOSU, "getcwd(", TYPE_SINK, None))
disclo.append(Target(CAT_DISCLOSU, "getlastmo(", TYPE_SINK, None))
disclo.append(Target(CAT_DISCLOSU, "getmygid(", TYPE_SINK, None))
disclo.append(Target(CAT_DISCLOSU, "getmyinode(", TYPE_SINK, None))
disclo.append(Target(CAT_DISCLOSU, "getmypid(", TYPE_SINK, None))
disclo.append(Target(CAT_DISCLOSU, "getmyuid(", TYPE_SINK, None))

dangerous = list()
dangerous.append(Target(CAT_DANGEROU, "extract(", TYPE_SINK, "# Opens the door for register_globals attacks (see study in scarlet)."))
dangerous.append(Target(CAT_DANGEROU, "parse_str(", TYPE_SINK, "# works like extract if only one argument is given."))
dangerous.append(Target(CAT_DANGEROU, "putenv(", TYPE_SINK, None))
dangerous.append(Target(CAT_DANGEROU, "ini_set(", TYPE_SINK, None))
dangerous.append(Target(CAT_DANGEROU, "mail(", TYPE_SINK, "# has CRLF injection in the 3rd parameter, opens the door for spam."))
dangerous.append(Target(CAT_DANGEROU, "header(", TYPE_SINK, "# on old systems CRLF injection could be used for xss or other purposes, now it is still a problem if they do a header('location: ...'); and they do not die();. The script keeps executing after a call to header(), and will still print output normally. This is nasty if you are trying to protect an administrative area."))
dangerous.append(Target(CAT_DANGEROU, "proc_nice(", TYPE_SINK, None))
dangerous.append(Target(CAT_DANGEROU, "proc_terminate(", TYPE_SINK, None))
dangerous.append(Target(CAT_DANGEROU, "proc_close(", TYPE_SINK, None))
dangerous.append(Target(CAT_DANGEROU, "pfsockopen(", TYPE_SINK, None))
dangerous.append(Target(CAT_DANGEROU, "fsockopen(", TYPE_SINK, None))
dangerous.append(Target(CAT_DANGEROU, "apache_child_terminate(", TYPE_SINK, None))
dangerous.append(Target(CAT_DANGEROU, "posix_kill(", TYPE_SINK, None))
dangerous.append(Target(CAT_DANGEROU, "posix_mkfifo(", TYPE_SINK, None))
dangerous.append(Target(CAT_DANGEROU, "posix_setpgid(", TYPE_SINK, None))
dangerous.append(Target(CAT_DANGEROU, "posix_setsid(", TYPE_SINK, None))
dangerous.append(Target(CAT_DANGEROU, "posix_setuid(", TYPE_SINK, None))

filesystem = list()
filesystem.append(Target(CAT_FILESYST, "fopen(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "tmpfile(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "bzopen(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "gzopen(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "SplFileObject(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "chgrp(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "chmod(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "chown(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "copy(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "file_put_contents(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "lchgrp(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "lchown(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "link(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "mkdir(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "move_uploaded_file(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "rename(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "rmdir(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "symlink(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "tempnam(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "touch(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "unlink(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "imagepng(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "imagewbmp(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "image2wbmp(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "imagejpeg(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "imagexbm(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "imagegif(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "imagegd(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "imagegd2(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "iptcembed(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "ftp_get(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "ftp_nb_get(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "file_exists(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "file_get_contents(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "file(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "fileatime(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "filectime(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "filegroup(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "fileinode(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "filemtime(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "fileowner(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "fileperms(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "filesize(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "filetype(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "glob(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "is_dir(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "is_executable(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "is_file(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "is_link(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "is_readable(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "is_uploaded_file(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "is_writable(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "is_writeable(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "linkinfo(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "lstat(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "parse_ini_file(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "pathinfo(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "readfile(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "readlink(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "realpath(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "stat(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "gzfile(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "readgzfile(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "getimagesize(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "imagecreatefromgif(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "imagecreatefromjpeg(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "imagecreatefrompng(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "imagecreatefromwbmp(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "imagecreatefromxbm(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "imagecreatefromxpm(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "ftp_put(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "ftp_nb_put(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "exif_read_data(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "read_exif_data(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "exif_thumbnail(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "exif_imagetype(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "hash_file(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "hash_hmac_file(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "hash_update_file(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "md5_file(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "sha1_file(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "highlight_file(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "show_source(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "php_strip_whitespace(", TYPE_SINK, None))
filesystem.append(Target(CAT_FILESYST, "get_meta_tags(", TYPE_SINK, None))

wordpress_specific = list()
wordpress_specific.append(Target(CAT_WP_SPECI, "update_site_option(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_blog_status(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_gallery_tab(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_posts_count(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_post_caches(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_site_option(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_user_caches(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_user_option(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_user_status(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_blog_details(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_comment_meta(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_home_siteurl(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_attached_file(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_comment_cache(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_network_cache(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_category_cache(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_network_option(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_postmeta_cache(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_sitemeta_cache(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_termmeta_cache(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_post_thumbnail_cache(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_network_option_new_admin_email(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_option_new_admin_email(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_nag(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_core(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_meta(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_option(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_archived(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_metadata(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_usermeta(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_post_meta(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_site_meta(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_term_meta(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_user_meta(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_meta_cache(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_page_cache(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_post_cache(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_site_cache(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_term_cache(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_blog_option(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_blog_public(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_metadata_by_mid(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_recently_edited(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_object_term_cache(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "update_right_now_message(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "set_post_format(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "set_current_user(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "set_user_setting(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "set_current_screen(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "set_post_thumbnail(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "set_screen_options(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "set_site_transient(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "set_post_thumbnail_size(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "set_post_type(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "set_query_var(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "set_theme_mod(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "set_transient(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "setup_postdata(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "setup_userdata(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "is_admin(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "check_admin_referer(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "current_user_can(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "is_super_admin(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "unserialize(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "maybe_unserialize(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "wp_query(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "json_decode(", TYPE_SINK, None))
wordpress_specific.append(Target(CAT_WP_SPECI, "http_request_args(", TYPE_SINK, None))
#wordpress_specific.append(Target(CAT_WP_SPECI, "admin_init(", TYPE_SINK, None))
#wordpress_specific.append(Target(CAT_WP_SPECI, "parse_request(", TYPE_SINK, None))
#wordpress_specific.append(Target(CAT_WP_SPECI, "init(", TYPE_SINK, None))
#wordpress_specific.append(Target(CAT_WP_SPECI, "the_content(", TYPE_SINK, None))
#wordpress_specific.append(Target(CAT_WP_SPECI, "wp_head(", TYPE_SINK, None))
#wordpress_specific.append(Target(CAT_WP_SPECI, "wp_footer(", TYPE_SINK, None))
#wordpress_specific.append(Target(CAT_WP_SPECI, "set_url_scheme(", TYPE_SINK, None))
#wordpress_specific.append(Target(CAT_WP_SPECI, "register_widget(", TYPE_SINK, None))
#wordpress_specific.append(Target(CAT_WP_SPECI, "add_action(", TYPE_SINK, None))
#wordpress_specific.append(Target(CAT_WP_SPECI, "do_action(", TYPE_SINK, None))
#wordpress_specific.append(Target(CAT_WP_SPECI, "add_filter(", TYPE_SINK, None))
#wordpress_specific.append(Target(CAT_WP_SPECI, "apply_filter(", TYPE_SINK, None))
#wordpress_specific.append(Target(CAT_WP_SPECI, "wp_doing_ajax(", TYPE_SINK, None))
#wordpress_specific.append(Target(CAT_WP_SPECI, "wp_verify_nonce(", TYPE_SINK, None))
#wordpress_specific.append(Target(CAT_WP_SPECI, "wp_ajax_nopriv_*(", TYPE_SINK, None))

php_magic = list()
php_magic.append(Target(CAT_PHP_MAGI, "__call(", TYPE_SINK, None))
php_magic.append(Target(CAT_PHP_MAGI, "__callStatic(", TYPE_SINK, None))
php_magic.append(Target(CAT_PHP_MAGI, "__get(", TYPE_SINK, None))
php_magic.append(Target(CAT_PHP_MAGI, "__set(", TYPE_SINK, None))
php_magic.append(Target(CAT_PHP_MAGI, "__isset(", TYPE_SINK, None))
php_magic.append(Target(CAT_PHP_MAGI, "__unset(", TYPE_SINK, None))
php_magic.append(Target(CAT_PHP_MAGI, "__sleep(", TYPE_SINK, None))
php_magic.append(Target(CAT_PHP_MAGI, "__wakeup(", TYPE_SINK, None))
php_magic.append(Target(CAT_PHP_MAGI, "__toString(", TYPE_SINK, None))
php_magic.append(Target(CAT_PHP_MAGI, "__invoke(", TYPE_SINK, None))
php_magic.append(Target(CAT_PHP_MAGI, "__set_state(", TYPE_SINK, None))
php_magic.append(Target(CAT_PHP_MAGI, "__clone(", TYPE_SINK, None))
php_magic.append(Target(CAT_PHP_MAGI, "__debugInfo(", TYPE_SINK, None))
php_magic.append(Target(CAT_PHP_MAGI, "__autoloa", TYPE_SINK, None))


# Sources
direct_input = list()
direct_input.append(Target(CAT_PHP_INPU, "$_GET", TYPE_SOURCE, None))
direct_input.append(Target(CAT_PHP_INPU, "$_POST", TYPE_SOURCE, None))
direct_input.append(Target(CAT_PHP_INPU, "$_REQUEST", TYPE_SOURCE, None))
direct_input.append(Target(CAT_PHP_INPU, "$_COOKIE", TYPE_SOURCE, None))
direct_input.append(Target(CAT_PHP_INPU, "$_SERVER", TYPE_SOURCE, None))
direct_input.append(Target(CAT_PHP_INPU, "$_SESSION", TYPE_SOURCE, None))
direct_input.append(Target(CAT_PHP_INPU, "$_FILES", TYPE_SOURCE, None))
direct_input.append(Target(CAT_PHP_INPU, "$GLOBALS", TYPE_SOURCE, None))

# Total
targets = list()
targets += command_exec
targets += php_exec
targets += callbacks
targets += disclo
targets += dangerous
targets += filesystem
targets += wordpress_specific
targets += direct_input
targets += php_magic

targets = sorted(targets, key=lambda x: len(x.name), reverse=True)
